#!/bin/bash


# We must have xterm installed.
if ! which xterm ; then
    echo "xterm not found"
    exit 1
fi


COUNTFILE=/tmp/$(whoami)_Ycounter_termRun

function restartCounter()
{
    echo "24" > $COUNTFILE # in pixels
}

function reset()
{
    # Remove all tmp history files and counter files
    # if there are any
    rm -f /tmp/*_termRun

    restartCounter
    echo "reset the terminal y offset counter"
    exit
}


[ -z "$*" ] && reset
[ ! -e $COUNTFILE ] && restartCounter


y_offset=356

y=$(cat $COUNTFILE) # in pixels
geo="-geometry 195x25+8+$y"

let y=${y}+$y_offset

echo "$y" > $COUNTFILE

title="$*"

term="xterm $geo"


HISTFILE=$(mktemp --suffix=_termRun)

echo "$*" > $HISTFILE

set -x
#
# Figuring out how to escape this command string was very painful:
#
$term -title "$title" -e bash -c "$* ; HISTFILE=$HISTFILE bash -i ; rm -f $HISTFILE" &

#while true ; do sleep 1 ; done

