

BUILD_NO_INSTALL := simple_parse

simple_parse_SOURCES := simple_parse.c

#JANSSON_ROOT := /usr/local
#simple_parse_CPPFLAGS := -I$(JANSSON_ROOT)/include 

simple_parse_LDFLAGS := -ljansson

include ../../quickbuild.make
