
BUILD_NO_INSTALL := webLauncher_programs/server_state.json


webLauncher_programs/server_state.json:
	cp webLauncher_programs/server_state.json_example webLauncher_programs/server_state.json


include ../quickbuild.make
