# This directory just contains some shared C/C++ files that may
# be accessed from ../bin or ../share/ and so on.

# This nothing to install from this directory.
# There to install files built in this directory
INSTALL_DIR = $(PREFIX)/lib/pkgconfig

INSTALLED := crts.pc

include ../../quickbuild.make
