
# There to install files from in this directory
INSTALL_DIR = $(PREFIX)/include/crts


INSTALLED :=\
 MakeModule.hpp\
 Module.hpp\
 Filter.hpp\
 Control.hpp\
 Controller.hpp\
 usrp_set_parameters.hpp\
 crts.hpp\
 debug.h


include ../../quickbuild.make
