#!/bin/bash

set -xe
cd $(dirname $0)

make -C ..

cat /dev/urandom | ../bin/crts_radio -f stdin -f liquidFrame\
 -f tx [ --control tx --uhd addr=192.168.10.2 --freq 915.5 --rate 0.2 --gain 15 ]\
 -c -f rx [ --uhd addr=192.168.10.4  --freq 915.5 --rate 0.2 --gain 0 ]\
 -f liquidSync -f stdout -c -C webClient -D > /dev/null
