#!/bin/bash

hostname=kermit.wireless.vt.edu
https_port=9090


set -euxo pipefail

cd $(dirname ${BASH_SOURCE[0]})



server=../bin/crts_contestWebServer
find_devices="../bin/crts_findUSRPs addr"

function PrintURL() {

    # wait a little so this print shows after the server spew
    # TODO: have this test if the server is up, instead of sleep.
    sleep 2
cat << EOF

Try:



  https://${hostname}:${https_port}/3dspectrum/?user=admin&password=admin123



EOF
}

# We'll generate a script for each USRP that we find

# Remove the old scripts
rm -f webLauncher_programs/SpectrumFeed/*

mkdir -p webLauncher_programs/SpectrumFeed

usrps="$(${find_devices})"


for addr in $usrps ; do
    file=webLauncher_programs/SpectrumFeed/addr_${addr}
    cat << EOF > $file
#!/bin/bash

set -ex

cd \$(dirname \${BASH_SOURCE[0]})

exec ../spectrumFeed -d addr=${addr}
EOF
    chmod 755 $file
    done


PrintURL& # this will print URL after some short time

$server\
 --https_port $https_port\
 --http_port 9091\
 --user=admin --password=admin123\
 --launcher_dir webLauncher_programs\
 --debug

