#!/bin/bash

##############################################################
# configure here
tag=${NOPOLL_TAG:-'0.4.6'}

# sha512sum is optional
sha512sum=25d3c550e3e094f1faece1f4333e8574efac74042b97de\
f86b0ec8ccc6060a6014359cec4fca893ef14d8aa845f7804734775f\
db562a06807c9a72d6a7ec8757

source ../GetSrcFromGithub.bash

#Usage: GetSrcFromGithub user package tag tarname [sha512sum]

GetSrcFromGithub ASPLes nopoll $tag nopoll $sha512sum
