#!/bin/bash

set -ex

cd $(dirname ${BASH_SOURCE[0]})

crts_radio=../../bin/crts_radio

exec $crts_radio\
 -f tests/count\
 -f throttle [ --bytes 17 --period 2 ]\
 -f tests/countCheck\
 -C webClient\
 $*

