#!/bin/bash

set -ex

cd $(dirname ${BASH_SOURCE[0]})

crts_radio="../../bin/crts_radio"

source usrp_config

tx=$CRTS_UPLOAD_DIR/tx_${LAUNCH_ID}
rx=$CRTS_UPLOAD_DIR/rx_${LAUNCH_ID}


$crts_radio\
 -f tests/count [ --name count ]\
 -f liquidFrame\
 -f tx [ --uhd $USRP1 --freq 914.5 --rate 0.2 --gain 15 ]\
 -C logger [\
 --file $tx liquidFrame totalBytesIn totalBytesOut ]\
 -C webClient\
 -D\
 &

pid1=$!


$crts_radio\
 -f rx [ --uhd $USRP2 --freq 914.5 --rate 0.2 --gain 0 ]\
 -f liquidSync\
 -f tests/countCheck\
 -C logger [\
 --file $rx liquidSync totalBytesIn totalBytesOut ]\
 -C webClient\
 -D\
 &

pid2=$!


function catch()
{
    kill -TERM $pid1 $pid2
}


trap catch SIGTERM

while wait; do echo "$$ $0 Waiting"; done

echo "$$ $0 exiting"
