#!/bin/bash

set -e
cd $(dirname ${BASH_SOURCE[0]})

source ./config
source ./1_config

USRP="$tx_usrp"

crts_radio="../../bin/crts_radio"

 $crts_radio\
 -f stdin\
 -f liquidFrame\
 -f tx [ --name tx1 --uhd "$USRP $UHD_ARGS" --freq 915.5 --rate $rate --resampFactor 3 --gain 31.5 ]\
 -C webClient < /dev/urandom


 #-C dualTx\

 # See it with:
 #
 #  uhd_fft --samp-rate 3000000 -f 915500000 -a addr=192.168.40.108
