#!/bin/bash

set -e
cd $(dirname ${BASH_SOURCE[0]})

if [ -z "$5" ] ; then
    cat << EOF
  Usage: $0 USRP RATE FREQ RESAMP_FACTOR GAIN

  We had to add a commandline argument so that both the javaScript and
  this script used the same USPR device, sample rate in MHz, center
  frequency in MHz, resample factor as a number, and gain in dB.

  Example, try running this:

       $0 addr=192.168.40.211 3.57 919.5 0.4 31.5

EOF
    exit 1
fi

USRP="$1"
rate="$2"
freq="$3"
resampFactor="$4"
gain="$5"


crts_radio="../../bin/crts_radio"

 $crts_radio\
 -f rx [\
 --name rx2\
 --uhd "$USRP"\
 --freq $freq\
 --rate $rate\
 --resampFactor $resampFactor\
 --gain $gain\
 ]\
 -f liquidSync\
 -f stdout\
 -C webClient_rate > /dev/null
