#!/bin/bash

# crts_spectrumFeed depends on a grc flowgraph 
# that uses gr-specest

#
# To see possible options args run:
#  ../../bin/crts_spectrumFeed2 --help
#


set -ex


# change working directory to this directory.
cd $(dirname ${BASH_SOURCE[0]})


spectrumFeed="../../bin/crts_spectrumFeed2"

exec $spectrumFeed\
 --period 0.1\
 --bandwidth 4.0\
 $*
