SUBDIRS := css js img

INSTALL_DIR = $(PREFIX)/htdocs

INSTALLED := doc

# we must tell quickbuild that x3dom is a directory
CLEANDIRS := x3dom
CLEANERFILES := x3dom.tar.gz.BAD_SHA512

include ../quickbuild.make
