#!/bin/bash

#
# To see possible options args run:
#  ../../bin/crts_spectrumFeed --help
#


set -ex


# change working directory to this directory.
cd $(dirname ${BASH_SOURCE[0]})

source ./1_config

spectrumFeed="../../bin/crts_spectrumFeed"

exec $spectrumFeed\
 --device $spectrum_usrp\
 --period 0.1\
 --freq 914.5\
 --bandwidth 4.0\
 $*
