#!/bin/bash

set -e
cd $(dirname ${BASH_SOURCE[0]})

USRP="addr=192.168.40.107"

crts_radio="$HOME/git/crts/bin/crts_radio"

 $crts_radio\
 -f stdin\
 -f liquidFrame\
 -f tx [ --uhd $USRP --freq 915.5 --rate 1 --gain 31.5 ]\
 -C webClient < /dev/urandom


 #-C dualTx\

 # See it with:
 #
 #  uhd_fft --samp-rate 3000000 -f 915500000 -a addr=192.168.40.108
