#!/bin/bash

set -e
cd $(dirname ${BASH_SOURCE[0]})

source ./2_config

USRP="$rx_usrp"

crts_radio="../../bin/crts_radio"

 $crts_radio\
 -f rx [ --name rx2 --uhd $USRP --freq $freq --rate 1 --gain 31.5 ]\
 -f liquidSync\
 -f stdout\
 -C webClient_rate > /dev/null
