#!/bin/bash

set -e
cd $(dirname ${BASH_SOURCE[0]})

source ./2_config

USRP="$rx_usrp"

crts_radio="$HOME/git/crts/bin/crts_radio"

 $crts_radio\
 -f rx [ --uhd $USRP --freq $freq --rate 1 --gain 31.5 ]\
 -f liquidSync\
 -f stdout\
 -C webClient > /dev/null
