#!/bin/bash

set -e
cd $(dirname ${BASH_SOURCE[0]})

USRP="addr=192.168.40.211"

crts_radio="$HOME/git/crts/bin/crts_radio"

 $crts_radio\
 -f rx [ --uhd $USRP --freq 915.5 --rate 1 --gain 31.5 ]\
 -f liquidSync\
 -f stdout\
 -C webClient > /dev/null
