#!/bin/bash

#
# To see possible options args run:
#  ../../bin/crts_spectrumFeed --help
#


set -ex

# change working directory to this directory.
cd $(dirname ${BASH_SOURCE[0]})

spectrumFeed="$HOME/git/crts/bin/crts_spectrumFeed"

exec $spectrumFeed\
 --device addr=192.168.40.111\
 --period 0.1\
 --freq 914.5\
 --bandwidth 4.0\
 $*
