#!/bin/bash

set -e
cd $(dirname ${BASH_SOURCE[0]})

#spectrum    192.168.40.111
#tx          192.168.40.112
#rx          192.168.40.211
#inferterer  192.168.40.212

USRP="addr=192.168.40.112"

crts_radio="$HOME/git/crts/bin/crts_radio"

 $crts_radio\
 -f stdin\
 -f liquidFrame\
 -f tx [ --uhd $USRP --freq 915.5 --rate 1 --gain 31.5 ]\
 -C webClient < /dev/urandom
