#!/bin/bash
set -e
cd $(dirname ${BASH_SOURCE[0]})

source ./2_config

USRP="$tx_interferer_usrp"

crts_radio="$HOME/git/crts/bin/crts_radio"

 $crts_radio\
 -f stdin\
 -f liquidFrame\
 -f tx [ --name tx2_interferer --uhd $USRP --freq $ifreq --rate 0.602410 --gain 31.5 ]\
 -C webClient < /dev/urandom
