#!/bin/bash

set -e
cd $(dirname ${BASH_SOURCE[0]})


USRP="addr=192.168.40.212"

crts_radio="$HOME/git/crts/bin/crts_radio"

 $crts_radio\
 -f stdin\
 -f liquidFrame\
 -f tx [ --name tx_interferer --uhd $USRP --freq 914.2 --rate 1 --gain 31.5 ]\
 -C webClient < /dev/urandom
