#!/bin/bash

set -e
cd $(dirname ${BASH_SOURCE[0]})

source ./2_config

USRP="$tx_usrp"

crts_radio="$HOME/git/crts/bin/crts_radio"

 $crts_radio\
 -f stdin\
 -f liquidFrame\
 -f tx [ --name tx2 --uhd $USRP --freq $freq --rate 1 --gain 31.5 ]\
 -C webClient < /dev/urandom
