#!/bin/bash

# crts_spectrumFeed2 depends on a grc flowgraph 
# that uses gr-specest. Furthermore, the python 
# environment variable needs to be sourced this way:
#
#
# $ source ~/.bashrc
#
# where bashrc contains:
# export PYTHONPATH=/usr/local/lib/python3/dist-packages:usr/local/lib/python2.7/site-packages:$PYTHONPATH
# export LD_LIBRARY_PATH=/user/local/lib:$LD_LIBRARY_PATH
#
# all of this above is specific to the vm called "pear"


#
# To see possible options args run:
#  ../../bin/crts_spectrumFeed2 --help
#

# The PREFIX where out of core GNUradio block module "gr-specest" is:
specest_root=/usr/local/encap/gr-specst-8b872b5-try-1

set -ex


# change working directory to this directory.
cd $(dirname ${BASH_SOURCE[0]})

# Add PYTHONPATH and stuff to environment
# so GNUradio can run.
_JUST_PATHS_=yes
# need these 2 exports for out of core GNUradio block module "gr-specest"
export PYTHONPATH=$specest_root/lib/python3.9/site-packages
export GRC_BLOCKS_PATH=$specest_root/share/gnuradio/grc/blocks
# grrun will add yet more crap to GRC_BLOCKS_PATH and PYTHONPATH and other
# stuff.
source /usr/local/bin/grrun


spectrumFeed="../../bin/crts_spectrumFeed2"

exec $spectrumFeed\
 --period 0.1\
 --bandwidth 4.0\
 $*
