#!/bin/bash

##############################################################
# configure here
uhd_tag=release_003_010_003_000
shm512sum=974f0121148f41d06d709f641c98655336ae91011\
dec46d18cb75f4290091ee975c3d9e77c6c284470efecdc6ef4\
2250a3278de0e37580193420148ffd9cc09e
##############################################################


source ../GetSrcFromGithub.bash

#Usage: GetSrcFromGithub user package tag tarname [sha512]

GetSrcFromGithub EttusResearch uhd $uhd_tag uhd $shm512sum
