#!/bin/bash

set -e

in=$0.IN.tmp
out=$0.OUT.tmp

# dd count blocks  1 block = 512bytes

dd if=/dev/urandom count=130 of=$in

../../bin/crts_radio\
 -f stdin\
 -f copy\
 -f stdout\
 < $in > $out

diff $in $out
echo "SUCCESS"
