#!/bin/bash

set -euo pipefail
shopt -s nullglob

cd $(dirname ${BASH_SOURCE[0]})

files=([0-9][0-9][0-9]*)
num=0
for run in "${files[@]}" ; do
    if [ -x $run ] ; then
        tests[$num]=$run
        let num=$num+1
    fi
done


i=1
pass=0
fail=0

echo "  ================================================"
echo "                RUNNING $num TESTS"
echo "  ================================================"
for run in "${tests[@]}" ; do
    echo "   [ $i / $num ] === running: $run"
    if ./$run ; then
        let pass=$pass+1
        echo "$run === PASSED"
    else
        let fail=$fail+1
        echo "$run === FAILED"
    fi

    let i=$i+1
done
echo
echo "  ================================================"
echo "                TOTAL TEST RESULTS"
echo "  ================================================"
echo -e "   [ $pass / $num ] PASSED"
echo -e "   [ $fail / $num ] FAILED"

[ $fail = 0 ] || exit 1

